"""Tests for the server-level ("Bucket A") half of app/ollama_tuning.py —
sanitize_server_env, render_env_file, write/read_server_env_file, and
server_env_status. These back the "Ollama server tuning" section of
Settings > System: values Ollama only reads from its own process
environment at start, written to a shared-volume env file for the ollama
container's entrypoint to source, since there is no runtime API to change
them. See app/ollama_tuning.py's module docstring for the full design.

Route-level tests (POST /settings/system's server-env handling) live in
tests/test_ollama_options.py, alongside the rest of that route's tests —
this file is scoped to the pure module functions.
"""
import os

import pytest

from app import ollama_tuning as tuning


# ── sanitize_server_env ─────────────────────────────────────────────────────

def test_sanitize_drops_unknown_keys():
    clean, errors = tuning.sanitize_server_env({"OLLAMA_HOST": "http://evil", "PATH": "/x"})
    assert clean == {}
    assert errors == []


def test_sanitize_choice_rejects_bad_value():
    clean, errors = tuning.sanitize_server_env({"OLLAMA_KV_CACHE_TYPE": "nope"})
    assert clean == {}
    assert len(errors) == 1
    assert "OLLAMA_KV_CACHE_TYPE" in errors[0]


def test_sanitize_choice_accepts_valid_value():
    clean, errors = tuning.sanitize_server_env({"OLLAMA_KV_CACHE_TYPE": "q8_0"})
    assert clean == {"OLLAMA_KV_CACHE_TYPE": "q8_0"}
    assert errors == []


def test_sanitize_int_bounds():
    clean, errors = tuning.sanitize_server_env({"OLLAMA_NUM_PARALLEL": "99"})
    assert clean == {}
    assert "between" in errors[0]

    clean, errors = tuning.sanitize_server_env({"OLLAMA_NUM_PARALLEL": "4"})
    assert clean == {"OLLAMA_NUM_PARALLEL": "4"}
    assert errors == []


def test_sanitize_int_rejects_non_numeric():
    clean, errors = tuning.sanitize_server_env({"OLLAMA_MAX_QUEUE": "lots"})
    assert clean == {}
    assert "whole number" in errors[0]


def test_sanitize_duration_accepts_common_forms():
    for value in ("30m", "-1", "0", "5h"):
        clean, errors = tuning.sanitize_server_env({"OLLAMA_KEEP_ALIVE": value})
        assert clean == {"OLLAMA_KEEP_ALIVE": value}, value
        assert errors == [], value


def test_sanitize_duration_rejects_garbage():
    clean, errors = tuning.sanitize_server_env({"OLLAMA_KEEP_ALIVE": "tomorrow"})
    assert clean == {}
    assert "duration" in errors[0]


def test_sanitize_rejects_shell_metacharacters():
    """Security-critical: the generated file is `.`-sourced by a POSIX shell
    in the ollama container's entrypoint, so a value containing shell
    metacharacters must never reach it."""
    clean, errors = tuning.sanitize_server_env({"HSA_OVERRIDE_GFX_VERSION": "11.0.0; rm -rf /"})
    assert clean == {}
    assert errors


def test_sanitize_rejects_spaces_and_quotes_in_tokens():
    clean, errors = tuning.sanitize_server_env({"ROCR_VISIBLE_DEVICES": "0 1"})
    assert clean == {}
    assert errors

    clean, errors = tuning.sanitize_server_env({"CUDA_VISIBLE_DEVICES": '"0"'})
    assert clean == {}
    assert errors


def test_sanitize_accepts_valid_token():
    clean, errors = tuning.sanitize_server_env({"ROCR_VISIBLE_DEVICES": "0,1"})
    assert clean == {"ROCR_VISIBLE_DEVICES": "0,1"}
    assert errors == []


def test_sanitize_blank_value_drops_the_key():
    clean, errors = tuning.sanitize_server_env({"OLLAMA_FLASH_ATTENTION": "  ", "OLLAMA_NUM_PARALLEL": "4"})
    assert clean == {"OLLAMA_NUM_PARALLEL": "4"}
    assert errors == []


def test_sanitize_missing_key_is_fine():
    clean, errors = tuning.sanitize_server_env({})
    assert clean == {}
    assert errors == []


# ── render_env_file ──────────────────────────────────────────────────────────

def test_render_env_file_is_deterministic():
    values = {"OLLAMA_NUM_PARALLEL": "4", "OLLAMA_FLASH_ATTENTION": "1"}
    a = tuning.render_env_file(values)
    b = tuning.render_env_file(dict(reversed(list(values.items()))))
    assert a == b
    # Key order follows SERVER_ENV_KEYS, not dict insertion order.
    assert a.index("OLLAMA_FLASH_ATTENTION") < a.index("OLLAMA_NUM_PARALLEL")


def test_render_env_file_omits_unset_keys():
    rendered = tuning.render_env_file({"OLLAMA_NUM_PARALLEL": "4"})
    assert "OLLAMA_NUM_PARALLEL=4" in rendered
    assert "OLLAMA_FLASH_ATTENTION" not in rendered


def test_render_env_file_empty_values_still_has_header():
    rendered = tuning.render_env_file({})
    assert rendered.startswith("# Generated by nd-world")
    lines = [ln for ln in rendered.splitlines() if ln.strip()]
    assert all(ln.startswith("#") for ln in lines)  # header comments only, no key=value line


# ── write_server_env / read_server_env_file ─────────────────────────────────

def test_write_and_read_roundtrip(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    values = {"OLLAMA_NUM_PARALLEL": "2", "OLLAMA_KV_CACHE_TYPE": "q8_0"}
    tuning.write_server_env(values)
    assert (tmp_path / tuning.ENV_FILENAME).is_file()
    assert tuning.read_server_env_file() == values


def test_write_server_env_creates_missing_directory(tmp_path, monkeypatch):
    target = tmp_path / "nested" / "config"
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", target)
    tuning.write_server_env({"OLLAMA_NUM_PARALLEL": "1"})
    assert (target / tuning.ENV_FILENAME).is_file()


def test_write_server_env_leaves_no_leftover_tmp_file(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    tuning.write_server_env({"OLLAMA_NUM_PARALLEL": "1"})
    assert list(tmp_path.glob("*.part")) == []


def test_read_server_env_file_returns_none_when_missing(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    assert tuning.read_server_env_file() is None


def test_read_server_env_file_ignores_comments_and_blank_lines(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    (tmp_path / tuning.ENV_FILENAME).write_text(
        "# a comment\n\nOLLAMA_NUM_PARALLEL=3\n   \n# more\nOLLAMA_FLASH_ATTENTION=1\n"
    )
    assert tuning.read_server_env_file() == {"OLLAMA_NUM_PARALLEL": "3", "OLLAMA_FLASH_ATTENTION": "1"}


def test_read_server_env_file_empty_file_is_empty_dict_not_none(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    (tmp_path / tuning.ENV_FILENAME).write_text("")
    assert tuning.read_server_env_file() == {}


# ── server_env_status ────────────────────────────────────────────────────────

def test_status_not_wired_when_no_applied_stamp(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    status = tuning.server_env_status({"OLLAMA_NUM_PARALLEL": "2"})
    assert status["writable"] is True
    assert status["wired"] is False
    assert status["pending"] is False
    assert status["applied"] is None


def test_status_pending_when_applied_differs(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    (tmp_path / tuning.APPLIED_FILENAME).write_text("OLLAMA_NUM_PARALLEL=1\n")
    status = tuning.server_env_status({"OLLAMA_NUM_PARALLEL": "2"})
    assert status["wired"] is True
    assert status["pending"] is True


def test_status_clean_when_applied_matches(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    (tmp_path / tuning.APPLIED_FILENAME).write_text("OLLAMA_NUM_PARALLEL=2\n")
    status = tuning.server_env_status({"OLLAMA_NUM_PARALLEL": "2"})
    assert status["wired"] is True
    assert status["pending"] is False


def test_status_reports_restart_commands(tmp_path, monkeypatch):
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", tmp_path)
    status = tuning.server_env_status({})
    assert status["restart_command"] == "docker compose restart ollama"
    assert "truenas-compose.yml" in status["restart_command_truenas"]


# os.geteuid() doesn't exist on Windows (the suite's original target was the
# Linux Docker container) — there, and for any non-root Unix user, the test runs.
@pytest.mark.skipif(hasattr(os, "geteuid") and os.geteuid() == 0, reason="root can write through a chmod 0o555 directory")
def test_status_reports_unwritable_dir(tmp_path, monkeypatch):
    target = tmp_path / "readonly"
    target.mkdir()
    target.chmod(0o555)
    monkeypatch.setattr(tuning, "OLLAMA_CONFIG_DIR", target)
    try:
        status = tuning.server_env_status({})
        assert status["writable"] is False
    finally:
        target.chmod(0o755)


# ── SERVER_ENV_SPEC / SERVER_ENV_HELP internal consistency ──────────────────

def test_server_env_keys_match_spec_order():
    assert tuning.SERVER_ENV_KEYS == tuple(spec[0] for spec in tuning.SERVER_ENV_SPEC)


def test_every_spec_entry_has_help_text():
    for env_key, *_rest in tuning.SERVER_ENV_SPEC:
        assert tuning.SERVER_ENV_HELP[env_key]


def test_rejected_env_vars_are_not_in_the_allowlist():
    """Documents the deliberate exclusions from app/ollama_tuning.py's module
    docstring — a form field must never be able to make Ollama unreachable
    (OLLAMA_HOST/OLLAMA_ORIGINS) or orphan its model store (OLLAMA_MODELS),
    or accept a free-text backend override (OLLAMA_LLM_LIBRARY)."""
    for rejected in ("OLLAMA_HOST", "OLLAMA_ORIGINS", "OLLAMA_MODELS", "OLLAMA_LLM_LIBRARY"):
        assert rejected not in tuning.SERVER_ENV_KEYS
