"""Built-in genre theme presets for a world's Visual Theme (World.theme_json).

Each entry is a complete, pre-validated theme object in exactly the shape
_sanitize_theme() (app/main.py) accepts from an uploaded JSON file — see
World.theme_json's docstring in app/models.py for what each field does.
tests/test_theme_presets.py asserts every entry here round-trips through
_sanitize_theme() unchanged, so a typo that would silently drop a field
(a bad hex digit, a font string with a disallowed character, ...) fails
the test suite instead of shipping a broken preset.

Applied via POST /worlds/{world_id}/theme/preset (world_theme_preset in
app/main.py) — the same effect as uploading the equivalent JSON through
/theme/import, just one click from a GM's own gallery of options instead
of hand-authoring a file. Keys are stable identifiers referenced by the
preset picker in world_edit.html and by the route's form field; renaming
one is a breaking change for that dropdown, not just cosmetic.
"""

THEME_PRESETS = {
    "dark_fantasy": {
        "name": "Dark Fantasy — Blood and Ash",
        "accent": "#9c2b2b",
        "bg": "#0a0808",
        "bg2": "#120e0e",
        "bg3": "#181212",
        "border": "#2a1f1f",
        "neon2": "#c9a227",
        "neon3": "#5b3a6e",
        "yellow": "#c9a227",
        "text": "#ded4c4",
        "text_dim": "#9c8f83",
        "font": "'Cormorant Garamond', Georgia, serif",
        "font_heading": "'Cinzel', Georgia, serif",
        "font_display": "'Cinzel Decorative', 'Cinzel', serif",
        "hero_letter_spacing": "-0.01em",
        "hero_glow_color": "#9c2b2b",
        "hero_graphic": "moon",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Cinzel:wght@500;700;900&family=Cinzel+Decorative:wght@700&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400&display=swap",
    },
    "high_fantasy": {
        "name": "High Fantasy — Gold and Azure",
        "accent": "#d4af37",
        "bg": "#0c0e1a",
        "bg2": "#12162a",
        "bg3": "#181d38",
        "border": "#2a3358",
        "neon2": "#3a5fcd",
        "neon3": "#2e8b57",
        "yellow": "#e8c86b",
        "text": "#e8e6d8",
        "text_dim": "#9aa0c0",
        "font": "'EB Garamond', Georgia, serif",
        "font_heading": "'Cinzel', Georgia, serif",
        "font_display": "'Cinzel Decorative', 'Cinzel', serif",
        "hero_letter_spacing": "0.02em",
        "hero_glow_color": "#d4af37",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Cinzel:wght@500;700;900&family=Cinzel+Decorative:wght@700&family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400&display=swap",
    },
    "post_apocalypse": {
        "name": "Post-Apocalypse — Rust and Ash",
        "accent": "#c1502e",
        "bg": "#0d0c09",
        "bg2": "#14120d",
        "bg3": "#1c1913",
        "border": "#332d22",
        "neon2": "#8fae2b",
        "neon3": "#6e6a5e",
        "yellow": "#c9b23a",
        "text": "#d8cdb8",
        "text_dim": "#948a76",
        "font": "'Special Elite', 'Courier New', monospace",
        "font_heading": "'Bebas Neue', sans-serif",
        "font_display": "'Bebas Neue', sans-serif",
        "hero_letter_spacing": "0.08em",
        "hero_glow_color": "#c1502e",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Special+Elite&family=Bebas+Neue&display=swap",
    },
    "horror": {
        "name": "Horror — Crimson Night",
        "accent": "#b0181f",
        "bg": "#060505",
        "bg2": "#0c0909",
        "bg3": "#110d0d",
        "border": "#241616",
        "neon2": "#6d0f14",
        "neon3": "#8a8a8a",
        "yellow": "#a89c8a",
        "text": "#cfc7c5",
        "text_dim": "#857c7a",
        "font": "'Crimson Text', Georgia, serif",
        "font_heading": "'Special Elite', 'Courier New', monospace",
        "font_display": "'Nosifer', cursive",
        "hero_letter_spacing": "0.03em",
        "hero_glow_color": "#b0181f",
        "hero_graphic": "moon",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Special+Elite&family=Crimson+Text:ital,wght@0,400;0,600;1,400&family=Nosifer&display=swap",
    },
    "pirate": {
        "name": "Pirate — Golden Age of Sail",
        "accent": "#c9a13b",
        "bg": "#0c0f0d",
        "bg2": "#131714",
        "bg3": "#1a1f1a",
        "border": "#2b332c",
        "neon2": "#1f6f6a",
        "neon3": "#8a3324",
        "yellow": "#d9b84a",
        "text": "#e2d9c2",
        "text_dim": "#948d78",
        "font": "'IM Fell English', Georgia, serif",
        "font_heading": "'Pirata One', cursive",
        "font_display": "'Pirata One', cursive",
        "hero_letter_spacing": "0.04em",
        "hero_glow_color": "#c9a13b",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Pirata+One&family=IM+Fell+English:ital@0;1&display=swap",
    },
    "sci_fi": {
        "name": "Sci-Fi — Cold Vacuum",
        "accent": "#2de2e6",
        "bg": "#05070d",
        "bg2": "#090c16",
        "bg3": "#0d111e",
        "border": "#1c2740",
        "neon2": "#ff9f1c",
        "neon3": "#7b61ff",
        "yellow": "#ffd166",
        "text": "#d6e4ff",
        "text_dim": "#7d8bb0",
        "font": "'Exo 2', sans-serif",
        "font_heading": "'Orbitron', sans-serif",
        "font_display": "'Orbitron', sans-serif",
        "hero_letter_spacing": "0.1em",
        "hero_glow_color": "#2de2e6",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700;900&family=Exo+2:ital,wght@0,400;0,600;1,400&display=swap",
    },
    "fantasy_sci_fi": {
        "name": "Fantasy Sci-Fi — Arcane Machine",
        "accent": "#a855f7",
        "bg": "#08050d",
        "bg2": "#0e0a16",
        "bg3": "#14101f",
        "border": "#2a2140",
        "neon2": "#e0b34d",
        "neon3": "#35d0e0",
        "yellow": "#e0b34d",
        "text": "#e3ddf0",
        "text_dim": "#9089ab",
        "font": "'Philosopher', sans-serif",
        "font_heading": "'Cinzel', Georgia, serif",
        "font_display": "'Orbitron', 'Cinzel', serif",
        "hero_letter_spacing": "0.05em",
        "hero_glow_color": "#a855f7",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Cinzel:wght@500;700;900&family=Orbitron:wght@700;900&family=Philosopher:ital,wght@0,400;0,700;1,400&display=swap",
    },
    "numenera": {
        "name": "Ninth World — Weird Science-Fantasy",
        "accent": "#4de6b0",
        "bg": "#06090a",
        "bg2": "#0a1012",
        "bg3": "#0e161a",
        "border": "#1c2f33",
        "neon2": "#c14ee0",
        "neon3": "#e0a83a",
        "yellow": "#e0a83a",
        "text": "#cfe8e0",
        "text_dim": "#7a9490",
        "font": "'Quantico', sans-serif",
        "font_heading": "'Michroma', sans-serif",
        "font_display": "'Michroma', sans-serif",
        "hero_letter_spacing": "0.12em",
        "hero_glow_color": "#4de6b0",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Michroma&family=Quantico:ital,wght@0,400;0,700;1,400&display=swap",
    },
    "stalker": {
        "name": "Zone Survival — Anomaly",
        "accent": "#8a9a3a",
        "bg": "#08090a",
        "bg2": "#0d0f10",
        "bg3": "#121415",
        "border": "#262a2b",
        "neon2": "#a14a2a",
        "neon3": "#4a5a63",
        "yellow": "#b8b04a",
        "text": "#c9cfc4",
        "text_dim": "#7c847a",
        "font": "'Roboto Condensed', sans-serif",
        "font_heading": "'Oswald', sans-serif",
        "font_display": "'Black Ops One', cursive",
        "hero_letter_spacing": "0.05em",
        "hero_glow_color": "#8a9a3a",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Oswald:wght@400;600;700&family=Black+Ops+One&family=Roboto+Condensed:ital,wght@0,400;0,700;1,400&display=swap",
    },
    "victorian": {
        "name": "Victorian — Gaslamp and Brass",
        "accent": "#7a1f2b",
        "bg": "#0b0908",
        "bg2": "#120f0d",
        "bg3": "#181412",
        "border": "#2e2620",
        "neon2": "#b08d3e",
        "neon3": "#2f4a3c",
        "yellow": "#b08d3e",
        "text": "#ddd0bd",
        "text_dim": "#9c8f7c",
        "font": "'Playfair Display', Georgia, serif",
        "font_heading": "'Playfair Display', Georgia, serif",
        "font_display": "'UnifrakturCook', cursive",
        "hero_letter_spacing": "normal",
        "hero_glow_color": "#b08d3e",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,700;1,400&family=UnifrakturCook:wght@700&display=swap",
    },
    "gothic": {
        "name": "Gothic — Cathedral and Moonlight",
        "accent": "#5b2a86",
        "bg": "#060509",
        "bg2": "#0b0910",
        "bg3": "#0f0c16",
        "border": "#221d2e",
        "neon2": "#8a2245",
        "neon3": "#b8b8c8",
        "yellow": "#b8b8c8",
        "text": "#d6d0dd",
        "text_dim": "#8a8496",
        "font": "'EB Garamond', Georgia, serif",
        "font_heading": "'Metamorphous', cursive",
        "font_display": "'UnifrakturMaguntia', cursive",
        "hero_letter_spacing": "-0.01em",
        "hero_glow_color": "#8a2245",
        "hero_graphic": "moon",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Metamorphous&family=UnifrakturMaguntia&family=EB+Garamond:ital,wght@0,400;0,600;1,400&display=swap",
    },
    "lovecraftian": {
        "name": "Lovecraftian — The Abyss Stares Back",
        "accent": "#5a8f6e",
        "bg": "#050608",
        "bg2": "#090b0e",
        "bg3": "#0d1013",
        "border": "#1c232a",
        "neon2": "#4a2e6e",
        "neon3": "#7fae9e",
        "yellow": "#7fae9e",
        "text": "#c8d2cc",
        "text_dim": "#7d8983",
        "font": "'Alegreya', serif",
        "font_heading": "'Almendra', serif",
        "font_display": "'Almendra SC', serif",
        "hero_letter_spacing": "0.03em",
        "hero_glow_color": "#5a8f6e",
        "hero_graphic": "circle",
        "google_fonts_url": "https://fonts.googleapis.com/css2?family=Almendra:ital,wght@0,400;0,700;1,400&family=Almendra+SC&family=Alegreya:ital,wght@0,400;0,700;1,400&display=swap",
    },
}
